### ISSUE TITLE
accept g.pocket log (xmlrpc)

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#328]
## TODO
- [x] document:
  - [x] general intentions
  - [x] user server side
  - [x] technical design
  - [x] user client side
- [x] implement server 3.1
  - [x] gui
  - [x] threading structure
  - [x] api - verify
  - [x] api - register
  - [x] api - get_snapshot
  - [x] api - put_change - split into #426
  - [x] api - put_picture
- [x] implement client
  - [x] gui
  - [x] code
- [ ] implement server 1.0
  - [ ] backport gui
  - [ ] copy code

we should really do this one, but it won't fit in the sprint:

- [ ] do not process a pocket-change if the last change to the plant, affecting that field, is newer than the timestamp of the pocket-line and it happened outside of the current `push` action.

## original report
we have a script for importing inventory data collected in g.pocket.
in the meanwhile, g.pocket has been expanded and can collect also pictures, and correction data, something that we had initially left to ODK Collect.
we have a script for importing data from the ODK Aggregator, and we should adapt it to importing data from the new g.pocket 'level 2' log.
sooner or later these scripts will be part of g.desktop.
we don't do this as yet, because the goal is not to import a file you need to manually copy from your phone, it is that you plug your phone to the desktop, and you manage all of it from ghini.desktop.

**Comment by mfrasca** [comment]
current format, not any more compatible with previous script:
timestamp :tag: tag-dependent-sequence
notice that the `PENDING_EDIT` may contain pictures, not present in this example.
```
20180427_134223 :INVENTORY: area91 : 2015.0091.1 : 000000000000000
20180427_134231 :INVENTORY: area91 : 2015.0092.1 : 000000000000000
20180427_134238 :INVENTORY: area91 : 2015.0093.1 : 000000000000000
20180427_134244 :INVENTORY: area91 : 2015.0094.1 : 000000000000000
20180427_134309 :PENDING_EDIT: 2015.0094.1 : Cecropia peltata : 3 : (@;@)
20180427_134340 :INVENTORY: area91 : 2015.0095.1 : 000000000000000
20180427_134354 :PENDING_EDIT: 2015.0095.1 : Bambusa vulgaris : 3 : (@;@)
20180427_134419 :INVENTORY: area91 : 2015.0044.1 : 000000000000000
20180427_134434 :PENDING_EDIT: 2015.0044.1 : Hippomane sp : 1 : (@;@)
20180427_134452 :INVENTORY: area91 : 2015.0045.1 : 000000000000000
```

if a `PENDING_EDIT` contains pictures, the line looks like this:
`20180223_182332 :PENDING_EDIT: 2015.0772.1 : Citrus : 3 : (-;-) : file:///storage/sdcard/Android/data/me.ghini.pocket/files/Pictures/GPP_20180223_181227-1539548640.jpg : file:///storage/sdcard/Android/data/me.ghini.pocket/files/Pictures/GPP_20180223_1812401204973253.jpg`

**Comment by mfrasca** [comment]
I'm reconsidering this one: instead of having ghini.desktop start this action, it would be ghini.pocket, that is, of the two ends, we initiate interaction at the weakest end.
### setup
you need a local network, and both devices connected to it, it could also just be the phone's hotspot.
in ghini.pocket, you need to configure the IP address of your desktop machine.
I don't think we need to configure the known machines, for the server is only running when a user starts it.
### action
- user puts ghini.desktop into `server` mode.  (this starts an `xml-rpc` server at the desktop.)
- click on 'send data' on pocket.
- review received data on desktop.
full stop.

**Comment by mfrasca** [comment]
![image](https://user-images.githubusercontent.com/122869/45110183-2e088d80-b107-11e8-834d-49d00b9194a9.png)

**Comment by mfrasca** [comment]
```
import sys
sys.path.append("/home/mario/Local/github/gturri/aXMLRPC/target/aXMLRPC-1.13.0-SNAPSHOT.jar")
from java.net import URL
from de.timroes.axmlrpc import XMLRPCClient
client = XMLRPCClient(URL("http://192.168.43.226:44464/API1"))
client.call('register', ['123', 'onhapf'])
```

**Comment by mfrasca** [comment]
```
20180427_134452 :INVENTORY: area91 : 2015.00945.1 : 000000000000000
20180427_134502 :INVENTORY: area91 : 2015.0045.1 : 000000000000000
20180427_134511 :INVENTORY: area91 : 2015.0044.1 : 000000000000000
20180427_134536 :INVENTORY: area91 : 2015.00944.1.1 : 000000000000000
20180427_134544 :INVENTORY: area91 : 2015.00944.1 : 000000000000000
20180501_085804 :INVENTORY:  : 2015.0001.1 : 000000000000000
20180905_170519 :PENDING_EDIT:  : Mangifera indica : null : (@;@) : file:///storage/sdcard/Android/data/me.ghini.pocket/files/Pictures/GPP_20180905_170500-440465989.jpg
20180905_170533 :INVENTORY:  : 2015.0021.1 : 000000000000000
20180905_170542 :INVENTORY:  : 2015.0022.1 : 000000000000000
20180905_170556 :INVENTORY:  : 2018.0001.1 : 000000000000000
20180905_170619 :PENDING_EDIT: 2018.0001.1 : Eugenia stipitata : 1 : (@;@)
20180905_170640 :INVENTORY:  : 2018.0002.1 : 000000000000000
20180905_170715 :PENDING_EDIT: 2018.0002.1 : Persea indica : 1 : (@;@)
20180905_170723 :INVENTORY:  : 2018.0003.1 : 000000000000000
20180905_171226 :PENDING_EDIT: 2018.0003.1 : Cecropia maxima : 1 : (@;@)
```

**Comment by mfrasca** [comment]
![image](https://user-images.githubusercontent.com/122869/45326214-a06ada80-b518-11e8-868d-9d15ce79cc22.png)
ghini.pocket able to verify identity with ghini.desktop, and able to register.

**Comment by mfrasca** [comment]
TODO: open an issue about porting this to 1.0
