### ISSUE TITLE
redefine user interaction in report generation

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#395]
## todo

I'll be rewriting the `glade` file, and partially fixing the `python` code.

- [x] the documentation describes the user interaction, the requirements for the templates, the whole logic behind this. (to be done in #394)
- [x] selecting/activating a template
  - [x] last used template is showed, or a hint "Choose or add template".
  - [x] offer list of active template names,
  - [x] let user remove the selected name from the active templates.
  - [x] let user activate a new template (browse and specify name).
  - [x] if user selects an already active template, reject it.
  - [x] if user defines already taken name, reject it.
  - [x] if user selects something that does not look like a template (no formatter can handle it), reject it.
- [x] the `report` template has a list of the registered formatter plugins.
- [x] each template must contain a `DOMAIN` declaration (use `raw` to work on top-level selection).
- [x] the gui asks each formatter plugin if it can handle each given template.
- [x] each template is relative to one formatter plugin.  the gui shows its name.
- [x] when template DOMAIN is `raw`, the iteration domain comes from the selection.
- [x] the gui shows the iteration domain.
- [x] [**skip**]specific plugins may have external dependencies (XSL: at least one rendering engine). if not satisfied, all templates needing this plugin cannot be invoked. (to be done in #413)
- specific plugins may need further settings (you must choose among the XSL engines).
  - [x] the graphic element is created once for all and lives the whole time in the interface, (#413)
  - [x] the report plugin sets it visible or invisible, depending on the plugin indicated by the template, (#413)
  - [x] [**skip**][**xsl**]if only one engine is available, just mention it (#413)
  - [x] [**xsl**]if several engines are available, let user choose (#413)
- [x] templates may have options.  the gui lets you associate values to expected options
- [x] ghini transforms the selection into the corresponding objects in the desired domain.
- [x] ghini may remove from consideration data marked as `private`.  (#414)
- [x] some feedback is given while producing the report so you don't thing the program got stuck.

### Actual behaviour
The Formatter Name window only lets you enter the name,
Once you do that, you get back to the Report Options window, and you can now dynamically indicate the Formatter **engine**.  This is a design mistake according to me.
The `Settings` expander is there that you can choose the report **template**.  Also a design mistake in my opinion.
As of now, the `Settings` expander does not expand.

### Expected behaviour
the Formatter Name window should let you specify **name**, **engine**, and **template** of the new formatter.
the formatter `Settings` should contain both the **engine** and the **template**, and it may be editable, but I'm not so sure about it.
Not all formatters have `Parameters`.  If they do, I think we should put them in a different expander, not in the `Settings`.

### further considerations

In ghini-1.0, the two formatters are implemented in seriously different ways, and I'm not so sure why this is so.  

- a Mako Template receives a list of values (the top-level selection), and it's its task to extract the pertinent objects of the desired type.

- the interface to the XSL Formatter lets the user specify the 'source type' (sounds to me like an other name for 'iteration domain') and the three possible values Accession/Plant/Species match the three functions `get_all_plants`, `get_all_accessions`, `get_all_species`.

- with the XSL Formatter you choose Stylesheet and Renderer, the Iteration Domain, and must indicate whether or not to use author names and private records.  
- Why is the 'author names' switch here and not in the Stylesheet, I fail to guess with the limited knowledge I have of the tool.
- I also wonder whether a stylesheet can be successfully perused with different 'source types'.  if, as I suspect, this is not the case, this indication should not stay in the user interface but go in the stylesheet itself.
- same question about the renderer.  is a stylesheet renderer-independent?

- the control 'include data marked as private' is repeated instead of shared.

I recently added a trick in Mako templates, letting the template request extra information (variables) that will influence the rendering.  it would be nice if we could find space in a XSL stylesheet, some syntax that allows us to do the same.  if so, the 'use author names' would be only asked if relevant.

### again further considerations

- on a system one has a possibly large collections of templates, that you want to consider, or you want to ignore.  the idea behind defining a name for one of them corresponds to making it visible to ghini, and to let the user decide a more mnemonic name for it.  but what's the reason for letting one associate two names to the same template?

- a template for Mako is a python/mako program and our templates start all with the text `## -*- coding: utf-8 -*-`.  XSL templates are XML files with first element: `xsl:stylesheet`.  so once you choose a template, you know which formatter you need.  why bother the user requesting that they first choose a formatter and then specify the template?  specifying the template should be enough, the user interface should then mention the formatter that will be used.

- in case of XSL formatter, the gui should ask that the user specifies the renderer.

- user runs a query so they have a selection.  then they request a report.  a report is relative to Species; Accession; Plant, or Location objects in the selection.  a report is designed to work on only one of these.  yet, for XSL reports, we ask the user to specify it again.  specifying the template should be enough, and the user interface should mention on what domain the report works.

**Comment by mfrasca** [comment]
`Presenter` and `View` are here re-implemented from scratch, instead of [derived from `editor.GenericEditorPresenter` and `editor.GenericEditorView`](https://ghini.readthedocs.io/en/ghini-3.1-dev/building.html#structure-of-user-interface).  this is going to take longer and I'm doubting whether I should do this also in ghini-1.0.

**Comment by mfrasca** [comment]
> But the big benefit of selecting the source is that it means you can use one template with different sources to get different outcomes

I wish I had one or two concrete examples for this.  the template, the settings, and the corresponding outcomes, on a very small selection.

a template declaring "raw" as DOMAIN name, makes ghini look at the top level objects from the results.  this also lets you work with species, accession, plant — same template.

>  I've often thought to myself that I wished it was easy to do this with mako templates.

if you wish something, then please mentioned in an issue.
I know, you always do, I know.

**Comment by mfrasca** [comment]
I can't picture what your example 1 means, in practice.  how do the different produced labels look like at your garden?  and how many would you print?  for example, what would you do with this:
![image](https://user-images.githubusercontent.com/122869/44790602-5c192b00-ab65-11e8-98f8-24734c40522d.png)

**Comment by mfrasca** [comment]
I finally installed Apache fop and I ran a couple of our included examples.  wow, are we really distributing such basic stuff…
![image](https://user-images.githubusercontent.com/122869/44801527-eae67180-ab7e-11e8-888d-0eaed0d2f547.png)

there seems to be no control on space occupation, and seems to be very little on formatting at all.  again, if you have some real life, usable, presentable labels, please share them, thank you!

the following are produced using two Mako templates which I wrote and you can find the software, first is postscript, meant for a label printer, second is svg, meant for a laser engraver.  we need a bit more work on limiting space occupation on the bottom line, and on aligning longer authorship texts, but the code is all there, we only miss users sponsoring (printer and/or laser).
![image](https://user-images.githubusercontent.com/122869/44801683-53cde980-ab7f-11e8-90b0-0b784da01f2d.png)
![image](https://user-images.githubusercontent.com/122869/44802064-55e47800-ab80-11e8-9812-1ac94b2d7112.png)

**Comment by mfrasca** [comment]
the gui while preparing to use the `basic.xsl` template.
query is: `accession where plants = Empty or sum(plants.quantity)=0`
![screenshot from 2018-08-29 17-46-51](https://user-images.githubusercontent.com/122869/44819726-8e517980-abb3-11e8-9e2f-a6747bb8a6de.png)

**Comment by mfrasca** [comment]
well, why is this taking so long.  the two template plugins look so much not interacting with each other, repeating code, solving the same problem differently, implementing logic that belongs elsewhere, that I think I am almost done, and I uncover a new conceptual mess… which sort of work, as long as you don't touch it.
so I'm not so sure how to continue, whether to continue…

**Comment by mfrasca** [comment]
![image](https://user-images.githubusercontent.com/122869/44889959-ccc36300-ac9d-11e8-958d-3dd3acb17282.png)
