### ISSUE TITLE
menu items in plug-in menus have no icons

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#396]
### TODO
- [x] invent something to associate icons to intermediate nodes
- [x] family
- [x] genus
- [x] species
- [x] accession
- [x] plant
- [x] location
- [x] contact
- [x] report
  - [x] template based
  - [x] quick templateless
- [x] institution
- [x] taxonomy check
- [x] backup
  - [x] create
  - [x] restore
- [x] export
- [x] import
- [x] tag current selection
- [x] apply active tag 
- [x] remove active tag 

### Expected behaviour
when you open a pull-down menu, the icons next to each menuitem help you recognize it and choose the one you need.
this should work both for end-points (eg: Family/Genus/Location) as well as for intermediate nodes (eg: Backup/Import/Export)

### Actual behaviour
this works fine in the File, Edit, and Help menus, but not so in the Insert, Tools, Tags menu (and I have not tested, but I suppose also in the Users menu).

![image](https://user-images.githubusercontent.com/122869/44302991-a34c2400-a2fa-11e8-9140-3a4d8b76572e.png)
![image](https://user-images.githubusercontent.com/122869/44302889-b90c1a00-a2f7-11e8-9b86-1f609c1a6e7a.png)
![image](https://user-images.githubusercontent.com/122869/44302987-90395400-a2fa-11e8-9583-1dc6c1ba2a98.png)

### Opinions and suggestions
in the Insert menu, we have items associated to the taxonomy plug-in, and items associated to the garden plug-in.  I would try to make the difference clearly visible.
For the rest, I would not know.  I would probably go sniffing around and see if there's any GPL software we can take as example.

**Comment by mfrasca** [comment]
the pluginmanager does not provide for menu items with images, we need to enhance it.
and since we are at it, we might just as well see what is messing up the order of the items. why are they alphabetically sorted instead of logically?  like: Family/Genus/Species (separator) Accession/Plant/Location (separator) Contact.

**Comment by mfrasca** [comment]
![image](https://user-images.githubusercontent.com/122869/44312523-5716e780-a3bf-11e8-9c0c-8422f9c1fe22.png)

**Comment by mfrasca** [comment]
![image](https://user-images.githubusercontent.com/122869/44608881-1f42e200-a7bb-11e8-8a15-23572a0525bc.png)

**Comment by mfrasca** [comment]
the ones relative to accession/plant/location are just a 'document-new' icon.
we could/should do something to distinguish them,
some time
