### ISSUE TITLE
Installing and launching version 3.1, 3.1 dev

### ISSUE THREAD

**Issue by exiledonamarginalisland** [Ghini/ghini.desktop#419]
let's say we want to be able to run both ghini-1.0 and ghini-3.1 on the same machine.  something like what allows you keep so many python versions all next to each other like this:
```
/usr/bin/python -> python2.7
/usr/bin/python2 -> python2.7
/usr/bin/python2.7
/usr/bin/python3 -> python3.5
/usr/bin/python3.5
```
not difficult, if we make sure that

### todo 
devinstall:

- [x] uses a different virtual environment location depending on the branch,
- [ ] produces a differently named script, also depending on the branch,
- [ ] (on unix) links the 'versioned' script to an unversioned one.
- [ ] lets the user decide whether to overwrite any pre-existing script

### original report
I am trying to install and launch version 3.1 and 3.1 dev in parallel to my 1.0.86. How do I do that? I have looked into the documentation and I do not seems to find anything. Apologies if the question is silly!

**Comment by mfrasca** [comment]
it's not a silly question and thanks for asking.
at the moment, the 3.1 line is not production-ready, (check #382).
you are welcome to test `ghini-3.1-dev` but be very much aware it is a **`-dev`** branch.
you may also follow the `ghini-3.1` branch, but again realize it is not production-ready.

as of now, if you want to install two ghini version next to each other and do it in a clean way, you would:
- fork the project
- clone your own fork
- for each branch you want to follow:
  - checkout the branch you want to follow
  - edit the `devinstall.sh`:
    - replace `ghide` with a branch-specific name,
    - append a version number to the ghini scripts and settings (outside the virtual environment),
  - commit your edit
  - run `devinstall.sh`

you can also just edit `devinstall.sh` after downloading it, and before running it.

if you handle the very basics of bash and virtualenv, it should not be complicated.  if you do not, then it would be easier for me to do provide the above "clean way" than to explain in detail what you have to change and how.

**Comment by mfrasca** [comment]
I don't think I'll to do all of it.  I think this is just enough to make life simpler to the 3 users who might be interested in using it.  and if anybody wants to complete the task, be my guest, I'm looking forward to merging your pull requests.

as it is now after this change:
- get your git clone (you probably already have it)
- `cd $HOME/Local/github/Ghini/ghini.desktop`
- make sure you have no local changes to be committed, and that you're up-to-date with github.
- then follow this sequence:
- `git checkout ghini-1.0`
- `./scripts/devinstall.sh`
- `cp $HOME/bin/ghini $HOME/bin/ghini10`
- `git checkout ghini-3.1`
- `./scripts/devinstall.sh`
- `cp $HOME/bin/ghini $HOME/bin/ghini31`

if you want to install both the development and the stable versions, you will need to do something very much along the same above lines.

**Comment by mfrasca** [comment]
at the moment, on my machine, I have three `~/bin/ghini*` scripts, and they only differ on their 3rd lines:

```
$ head -n4 ~/bin/ghini{,10,31}
==> /home/mario/bin/ghini <==
#!/bin/bash

GITHOME=/home/mario/Local/github/Ghini/ghini.desktop/
. $HOME/.virtualenvs/ghide-3.1-dev/bin/activate

==> /home/mario/bin/ghini10 <==
#!/bin/bash

GITHOME=/home/mario/Local/github/Ghini/ghini.desktop/
. $HOME/.virtualenvs/ghini-1.0/bin/activate

==> /home/mario/bin/ghini31 <==
#!/bin/bash

GITHOME=/home/mario/Local/github/Ghini/ghini.desktop/
. $HOME/.virtualenvs/ghini-3.1/bin/activate
```
