### ISSUE TITLE
we need order in template-based reports

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#431]
### todo:
- [ ] ON-HOLD define the concept of `resources` directory, sibling to `templates`.
- [x] create an intermediate class between `MakoFormatterPlugin` and `FormatterPlugin`, from which to derive `Jinja2FormatterPlugin`
- [x] have a single `templates` directory for package-templates
- [x] copy package-templates to module resources (at installation).
- [x] do not copy package-templates to user_dir (not implicitly).
- [x] package-templates are always found
- [x] make sure it still works (unit tests, then use cases)
- [x] add Jinja2 or Mako postscript base template (defining fonts).
- [x] add Jinja2 or Mako templates expanding base postscript template.
- [x] move postscript `add_text` out of templates, into plugin module.
- [x] add vertical stretching to `add_text`.
- [x] add horizontal squeezing to `add_text`.
- [x] create sample template (implies integration test)
- [x] examine https://bitbucket.org/zzzeek/mako/issues/280/
- [x] make `insert_picture` work with either PIL.Image object or filename.
- [x] let `insert_picture` work with Level (greyscale, ignoring Alpha)
- [x] let `insert_picture` work with RGB (colours, ignoring Alpha)
- [x] add the `PS` and the `SVG` namespaces and make them visible to Jinja2 and Mako
- [x] put a few more useful functions in the Jinja2 environment (Jinja2 templates can't import python).
- [x] configuration only holds options; if a template can be found, it is considered active.
- [x] copy template to user_dir when activating it (keeping name).
- [x] interface shows if a template is package- or user-template
- [x] names_ls is read once in own thread when opening dialog,
- [x] names_ls is expanded when user template is installed
- [x] names_ls is shrunk when template is removed
- [x] write better template authoring instructions.
- [x] package templates can be set as hidden (frozen)
- [x] the 'add template dialog' is defined in a glade file
- [x] the glade file definition for 'add template dialog' is used
- [x] you can choose to thaw all templates (from: add template dialog)

### second thoughts
postscript production is currently severely bulky: in each template we have font definitions, this even messes up github statistics, making the system consider postscript the main language for our project.  every template also contains copies of a couple of python functions which really belong in the report tool.  now we would be adding pictures, and I would rather have them as external resources, not as included postscript data.

### original notes
it is possible to include JPG data in PS files, but not out of the box, in the sense that we better provide some tools in the libs, that let us:
- convert a binary JPG file to something we can include in postscript
- produce the postscript commands that decode the above produced string to image data

PS lets us easily work with JPG (it contains the right decoder), while if we want to do PNG (lossless) then we need do more work in Python, like decoding the PNG then encoding possibly with LZW (known to PS) before going to ASCII.  I have not been successful with ASCII85.

please refer to [this Q&A on stackoverflow](https://stackoverflow.com/questions/4968443/simple-way-to-add-an-image-in-postscript/52502566#52502566).

if we want to do any other RGB format, consider we cannot do transparency (only True/False mask is available), we can go through PIL:

```
>>> import PIL.Image
>>> i = PIL.Image.open("/tmp/from-template.png")
>>> "".join("%02x%02x%02x" % k[:3] for k in i.getdata())
```

`convert image.png -background white -alpha remove white.png`

**Comment by mfrasca** [comment]
in the template authoring instructions, consider referring to the site: http://getdrawings.com/tropical-leaves-drawing

**Comment by mfrasca** [comment]
As mentioned in #434, I grew definitely fed up with the low quality of the Mako documentation.  I wanted to use inheritance in templates and from the Jinja2 docs I could produce a working example in 20 minutes, while I've spent no less than 2 hours trying to pin it down in Mako and did not manage.  So I'm leaving Mako for historical reasons and I'm moving to Jinja2.  Most utility functions still apply, obviously, as does this whole issue too.

**Comment by mfrasca** [comment]
`loader = ChoiceLoader([FileSystemLoader(), PackageLoader()])`, forsan
