### ISSUE TITLE
implement "Quick report" function

### ISSUE THREAD

**Issue by RoDuth** [Ghini/ghini.desktop#62]
## todo
- [x] decide name, we already have a csv exporter, for backup and restore
- [x] create interface and link to menus
- [x] generalize querybuilder logic
- [x] do not include foreign keys (available as id of linked object)
- [x] do not offer following links back to something already explored (like genus->species->genus)
- [x] offer string representation of object (species: genus.epithet+epithet; plant: accession.code+code)
- [x] `id` is really a counter, and should be treated as such, in `uselist` properties.
- [x] let user type name of output file
- [x] compute output
- [x] let user delete a row from the properties to export
- [x] let user use keyboard to change row order in properties to export
- [x] retain last status
- [x] write output
- [x] let user browse for output file
- [x] disable `execute` when no file name is given
- [x] after exporting, show informative dialog-box with statistics about the output, and offering opening it.
- [x] in the tools menu, move it from `export` to `report`
- [x] let the user decide whether to export everything, or only the selection. (now reported as #401)
- [x] once we produce the file, open it in the installed, associated program.

## original report
OK, I think this is my last for today.   Just getting all the things that I have been thinking about for a while but never generated an issue for down.  

I know this is a big one so just close it if you hate it.

In our old database you could run a search then select `export` from the menu and a simple window would pop up with a list of **all** the possible fields in your search on the left and an empty box on the right.  You could select what fields you wanted and move them across to the right hand box (it had `move all`, `clear all`, `move ->` and `move <-`  buttons between the two boxes), then put them into the order you wanted by dragging them up or down in the list.  Then select the field(s) you wanted the list sorted by (e.g. garden bed code, species, accession number, family, could even make it sort by garden bed code first then species below that, etc. etc.) and click export and it would generate a basic CSV file.   This was extremely handy for getting useful data out of the system quickly for various uses and made the data available to be used in so many more ways (for generating graphs or the like in a spreadsheet or creating a species lists within a report or presentation document)  The current system for reports is great and I love it for generating formatted documents straight out of the database (once you have a template) but sometimes you just want access to the raw data quickly for a once-of use in an irregular form and generating a template isn't really worth it.

You could have a "Quick Report" item on the Tools menu for this use.

**Comment by mfrasca** [comment]
it is indeed a big one. I wonder what you would do if you select plants and you want properties in the report which are stored in accessions or farther, e.g.: genus.epithet.
an example of selecting fields, you have it in the query builder.
I'm now guessing, but your _old database_ could offer you this functionality because it was holding all information in a single table. or wasn't it?

**Comment by RoDuth** [comment]
Dead right Mario, it was just a single table, essentially flat database.

The query builder would be a perfect model.

**Comment by mfrasca** [comment]
The query builder does indeed contain reusable code for this case.
![image](https://user-images.githubusercontent.com/122869/40878251-d5d51b9a-6653-11e8-954f-9e5f7d511056.png)

**Comment by mfrasca** [comment]
![a](https://user-images.githubusercontent.com/122869/40891644-0f9d3fe6-674f-11e8-87de-bba355df6781.png)

it doesn't do anything yet, and we should think about the meaning of exporting related fields.

when filtering fields, I would:
- not show fields ending with `_id` (internally meaningful).
- not show `id`.
- in relations one-to-many, only include numeric values, and collapse the multiple values into sum.
- in relations one-to-many, offer an extra `count` field.

**Comment by mfrasca** [comment]
todo:
- [ ] do not offer following links back to something already explored (like genus->species->genus)
- [ ] offer string representation of object (species: genus.epithet+epithet; plant: accession.code+code)
- [ ] `id` is really a counter, and should be treated as such, in `uselist` properties.

**Comment by RoDuth** [comment]
The work you have done here is great and I no doubt will have use for it but I should maybe have explained what I was looking for better.  I was looking for something that coud produce a report relevant to the current search. E.g. you search for say `family=Myrtaceae`, you can then print a "quick report" that shows the species and the locations we have them (here, to use the query builder as an analogy, you would choose plant as the domain then select acccession.species.genus.genus, accession.species.sp and location.code) but then you could also print a report from that same search that was accession number, species and the source for the accession (using accession as the domain...). 

...**Without** having to write a mako template each time. I have so many mako csv templates floating around now!  

This would give users a way to get data out without having to learn one of the template systems.  Something that was immediately accessible to users.

**Comment by mfrasca** [comment]
are you asking for a "constrain to selection"?

**Comment by mfrasca** [comment]
oh, you're suggesting **where to put the report** tool.  and you're suggesting to call it Tools->Export->From-Template.
that makes sens, yes.
on the other hand, this choice seems to me quite unrelated to the checkbox for exporting the selection/exporting the database, in the flat-file export.

**Comment by RoDuth** [comment]
No I'm suggesting:
Tools->Report->From-Template 
for the current system and
Tools->Report->Quick CSV
for the flat-file export tool with the output constrained.

> To me it was always about making a quick csv **report** not exporting

The idea being that it you can generate the data you want and send it to something that does have "a fancy report designer"like LibreCalc or Excel and that many office workers are already familiar with (or will have someone in their office that is) users could turn that into a report fairly quickly.
